Repository distributed-system-analysis/pbench-dashboard, pull requests merged in 2021-01, with the labels that each got.

#118 Update node version to 14 to handle updated dependencies
  .travis.yml
Labels: bug

#114 Dashboard support for ES7 / Pbench server 0.71
  .gitignore
  README.md
  mock/api.js
  package.json
  public/endpoints.js
  src/e2e/controllers.e2e.js
  src/e2e/results.e2e.js
  src/e2e/search.e2e.js
  src/e2e/session.e2e.js
  src/models/dashboard.js
  src/models/datastore.js
  src/models/search.js
  src/services/dashboard.js
  src/services/datastore.js
  src/services/search.js
Labels: bug, enhancement

#117 Update createdAt and updatedAt fields with defaults for Sessions type
  config/router.config.js
  mock/api.js
  prisma/datamodel.prisma
  prisma/src/resolvers.js
  prisma/src/typeDefs.js
  src/common/menu.js
  src/components/GlobalHeader/index.js
  src/components/SessionModal/index.js
  src/e2e/session.e2e.js
  src/layouts/BasicLayout.js
  src/models/explore.js
  src/models/global.js
  src/models/sessions.js
  src/pages/Explore/index.js
  src/pages/Explore/index.test.js
  src/pages/SessionPlaceholder/index.js
  src/pages/SessionPlaceholder/index.test.js
  src/pages/Sessions/index.js
  src/pages/Sessions/index.test.js
  src/services/explore.js
  src/services/global.js
  src/services/sessions.js
Labels: enhancement
